{% set name = "videohash" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/videohash-{{ version }}.tar.gz
  sha256: 64ba3876804c584a4ae22c70d4708eea08e559c2ea9ce8a7926a2894b4f38c2f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - imagehash
    - pillow
    - python >={{ python_min }}
    - youtube-dl
    - yt-dlp
    - imagedominantcolor

test:
  imports:
    - videohash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://akamhy.github.io/videohash/
  summary: videohash - Perceptual Video Hashing package
  dev_url: https://github.com/akamhy/videohash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
