{% set name = "videohash" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/videohash-{{ version }}.tar.gz
  sha256: 2c5e91d5f76de0e603ef3a1f25e4634e21016a0c8627a72cac67ede792d8b890

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - imagehash
    - pillow
    - imagedominantcolor
    - yt-dlp
    - python >=3.6
    
test:
  imports:
    - videohash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://akamhy.github.io/videohash/
  summary: videohash - Perceptual Video Hashing package
  dev_url: https://github.com/akamhy/videohash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
